services:

  _defaults:
    autowire: true
    autoconfigure: true

  AppBundle\Utils\TaskSpreadsheetParser:
    arguments:
      $countryCode: '%country_iso%'

  AppBundle\Utils\DeliverySpreadsheetParser:
    arguments:
      - "@coopcycle.geocoder"
      - "@coopcycle.tag_manager"
      - "@slugify"
      - "@libphonenumber.phone_number_util"
      - "%country_iso%"

  AppBundle\Form\ApiRegistrationType:
    arguments: ['%country_iso%']
    tags:
      - { name: form.type, alias: app_user_api_registration }

  AppBundle\Form\RegistrationType:
    arguments:
      $countryIso: '%country_iso%'
      $isDemo: '%is_demo%'
    tags:
      - { name: form.type }

  AppBundle\Form\UpdateProfileType:
    arguments: [ '@security.token_storage', '@translator', '%country_iso%' ]
    tags:
      - { name: form.type, alias: app_update_profile }

  AppBundle\Form\AddressType:
    arguments:
      $country: '%country_iso%'
    tags:
      - { name: form.type }

  AppBundle\Form\DeliveryAddressType:
    arguments: [ '@translator', '%country_iso%' ]
    tags:
      - { name: form.type }

  AppBundle\Form\DeliveryType:
    arguments:
      $routing: '@routing_service'
      $translator: '@translator'
      $authorizationChecker: '@security.authorization_checker'
      $country: '%country_iso%'
      $locale: '%kernel.default_locale%'
    tags: [ form.type ]

  AppBundle\Form\DeliveryEmbedType:
    parent: AppBundle\Form\DeliveryType
    autowire: false
    autoconfigure: false
    arguments:
      $settingsManager: '@coopcycle.settings_manager'
    tags: [ form.type ]

  AppBundle\Form\NewOrderType:
    parent: AppBundle\Form\DeliveryType
    autowire: false
    autoconfigure: false
    tags: [ form.type ]

  AppBundle\Form\OrderType:
    arguments: [ '@sm.factory', '@security.authorization_checker' ]
    tags: [ form.type ]

  AppBundle\Form\TaskUploadType:
    tags: [ form.type ]

  AppBundle\Form\AddUserType:
    arguments: [ '@doctrine' ]
    tags: [ form.type ]

  AppBundle\Form\PaymentType:
    arguments: [ '@sm.factory', '@security.authorization_checker' ]
    tags: [ form.type ]

  AppBundle\Form\TaskExportType:
    arguments: [ '@coopcycle.repository.task' ]
    tags: [ form.type ]

  AppBundle\Form\SettingsType:
    arguments:
      $country: '%country_iso%'
      $isDemo: '%is_demo%'
    tags: [ form.type ]

  AppBundle\Form\TaskType:
    arguments:
      $country: '%country_iso%'
    tags: [ form.type ]

  AppBundle\Form\RestaurantType:
    arguments:
      $country: '%country_iso%'
      $loopeatEnabled: '%loopeat_enabled%'
    tags: [ form.type ]

  AppBundle\Form\StoreType:
    arguments:
      $country: '%country_iso%'
      $loopeatEnabled: '%loopeat_enabled%'
    tags: [ form.type ]

  AppBundle\Form\ProductOptionType:
    arguments: [ '@translator' ]
    tags: [ form.type ]

  AppBundle\Form\MenuEditor\TaxonProductType:
    arguments: [ '@sylius.repository.product' ]
    tags: [ form.type ]

  AppBundle\Form\ProductType:
    arguments:
      - '@sylius.factory.product_variant'
      - '@sylius.product_variant_resolver.default'
      - '@sylius.repository.product_attribute'
      - '@sylius.factory.product_attribute_value'
      - '@sylius.locale_provider'
      - '@translator'
    tags: [ form.type ]

  AppBundle\Form\Checkout\CheckoutAddressType:
    arguments:
      $country: '%country_iso%'
    tags: [ form.type ]

  AppBundle\Form\ApiAppType:
    arguments:
      - '@Trikoder\Bundle\OAuth2Bundle\Manager\ClientManagerInterface'
    tags: [ form.type ]

  AppBundle\Form\MaintenanceType:
    arguments:
      - '@snc_redis.default'
    tags: [ form.type ]

  AppBundle\Form\AddressBookType:
    tags: [ form.type ]

  sylius.form.extension.type.promotion_coupon:
    class: AppBundle\Form\Extension\PromotionCouponTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Sylius\Bundle\PromotionBundle\Form\Type\PromotionCouponType }

  sylius.form.type.promotion_rule.premium_customer_configuration:
    class: AppBundle\Form\Sylius\Promotion\Rule\IsCustomerConfigurationType
    tags:
        - { name: form.type }

  AppBundle\Form\Order\CartType:
    tags: [ form.type ]

  AppBundle\Form\Type\TimeSlotChoiceType:
    arguments:
      $country: '%country_iso%'
      $locale: '%kernel.default_locale%'
    tags: [ form.type ]

  AppBundle\Form\Type\MoneyType:
    tags: [ form.type ]

  AppBundle\Form\DeliveryImportType:
    tags: [ form.type ]

  AppBundle\Form\ProductOptionWithPositionType:
    tags: [ form.type ]

  AppBundle\Form\TimeSlotType:
    tags: [ form.type ]

  AppBundle\Form\OrderExportType:
    tags: [ form.type ]

  AppBundle\Form\Type\LocalBusinessTypeChoiceType:
    tags: [ form.type ]

  AppBundle\Form\Sylius\Promotion\OfferDeliveryType:
    arguments:
      $promotionRuleFactory: '@sylius.factory.promotion_rule'
    tags: [ form.type ]
